//
//
// Copyright 2018 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file echo/echo.proto (package grpc.examples.echo, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file echo/echo.proto.
 */
export const file_echo_echo: GenFile = /*@__PURE__*/
  fileDesc("Cg9lY2hvL2VjaG8ucHJvdG8SEmdycGMuZXhhbXBsZXMuZWNobyIeCgtFY2hvUmVxdWVzdBIPCgdtZXNzYWdlGAEgASgJIh8KDEVjaG9SZXNwb25zZRIPCgdtZXNzYWdlGAEgASgJMvsCCgRFY2hvElAKCVVuYXJ5RWNobxIfLmdycGMuZXhhbXBsZXMuZWNoby5FY2hvUmVxdWVzdBogLmdycGMuZXhhbXBsZXMuZWNoby5FY2hvUmVzcG9uc2UiABJcChNTZXJ2ZXJTdHJlYW1pbmdFY2hvEh8uZ3JwYy5leGFtcGxlcy5lY2hvLkVjaG9SZXF1ZXN0GiAuZ3JwYy5leGFtcGxlcy5lY2hvLkVjaG9SZXNwb25zZSIAMAESXAoTQ2xpZW50U3RyZWFtaW5nRWNobxIfLmdycGMuZXhhbXBsZXMuZWNoby5FY2hvUmVxdWVzdBogLmdycGMuZXhhbXBsZXMuZWNoby5FY2hvUmVzcG9uc2UiACgBEmUKGkJpZGlyZWN0aW9uYWxTdHJlYW1pbmdFY2hvEh8uZ3JwYy5leGFtcGxlcy5lY2hvLkVjaG9SZXF1ZXN0GiAuZ3JwYy5leGFtcGxlcy5lY2hvLkVjaG9SZXNwb25zZSIAKAEwAUI1WjNnb29nbGUuZ29sYW5nLm9yZy9ncnBjL2V4YW1wbGVzL2ZlYXR1cmVzL3Byb3RvL2VjaG9iBnByb3RvMw");

/**
 * EchoRequest is the request for echo.
 *
 * @generated from message grpc.examples.echo.EchoRequest
 */
export type EchoRequest = Message<"grpc.examples.echo.EchoRequest"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message grpc.examples.echo.EchoRequest.
 * Use `create(EchoRequestSchema)` to create a new message.
 */
export const EchoRequestSchema: GenMessage<EchoRequest> = /*@__PURE__*/
  messageDesc(file_echo_echo, 0);

/**
 * EchoResponse is the response for echo.
 *
 * @generated from message grpc.examples.echo.EchoResponse
 */
export type EchoResponse = Message<"grpc.examples.echo.EchoResponse"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message grpc.examples.echo.EchoResponse.
 * Use `create(EchoResponseSchema)` to create a new message.
 */
export const EchoResponseSchema: GenMessage<EchoResponse> = /*@__PURE__*/
  messageDesc(file_echo_echo, 1);

/**
 * Echo is the echo service.
 *
 * @generated from service grpc.examples.echo.Echo
 */
export const Echo: GenService<{
  /**
   * UnaryEcho is unary echo.
   *
   * @generated from rpc grpc.examples.echo.Echo.UnaryEcho
   */
  unaryEcho: {
    methodKind: "unary";
    input: typeof EchoRequestSchema;
    output: typeof EchoResponseSchema;
  },
  /**
   * ServerStreamingEcho is server side streaming.
   *
   * @generated from rpc grpc.examples.echo.Echo.ServerStreamingEcho
   */
  serverStreamingEcho: {
    methodKind: "server_streaming";
    input: typeof EchoRequestSchema;
    output: typeof EchoResponseSchema;
  },
  /**
   * ClientStreamingEcho is client side streaming.
   *
   * @generated from rpc grpc.examples.echo.Echo.ClientStreamingEcho
   */
  clientStreamingEcho: {
    methodKind: "client_streaming";
    input: typeof EchoRequestSchema;
    output: typeof EchoResponseSchema;
  },
  /**
   * BidirectionalStreamingEcho is bidi streaming.
   *
   * @generated from rpc grpc.examples.echo.Echo.BidirectionalStreamingEcho
   */
  bidirectionalStreamingEcho: {
    methodKind: "bidi_streaming";
    input: typeof EchoRequestSchema;
    output: typeof EchoResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_echo_echo, 0);

